final-rails/config/routes.rb
Rails.application.routes.draw do
  resources :songs
  resources :playlists
  get 'guest/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "guest#index"
end

final-rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

final-rails/app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_many :playlist_songs, dependent: :destroy
  has_many :songs, through: :playlist_songs
end

final-rails/app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :playlist
  belongs_to :song
end

final-rails/app/models/song.rb
class Song < ApplicationRecord
  has_many :playlist_songs, dependent: :destroy
  has_many :playlists, through: :playlist_songs
end

final-rails/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :playlists, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

final-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

final-rails/app/controllers/guest_controller.rb
class GuestController < ApplicationController
  before_action :set_playlists 
  def index
    if user_signed_in?
      redirect_to playlists_path()
    end
  end

  private
    def set_playlists
      @playlists = Playlist.all
    end

    def playlist_params
      params.require(:playlist).permit(:title, :description)
    end
end

final-rails/app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /playlists or /playlists.json
  def index
    @playlists = Playlist.all
  end

  # GET /playlists/1 or /playlists/1.json
  def show
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists or /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: "Playlist was successfully created." }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1 or /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: "Playlist was successfully updated." }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1 or /playlists/1.json
  def destroy
    @playlist.destroy!

    respond_to do |format|
      format.html { redirect_to playlists_path, status: :see_other, notice: "Playlist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def playlist_params
      params.require(:playlist).permit(:title, :description, :user_id, song_ids: [])
    end
end

final-rails/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: %i[ show edit update destroy ]

  # GET /songs or /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1 or /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs or /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: "Song was successfully created." }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1 or /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: "Song was successfully updated." }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1 or /songs/1.json
  def destroy
    @song.destroy!

    respond_to do |format|
      format.html { redirect_to songs_path, status: :see_other, notice: "Song was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def song_params
      params.require(:song).permit(:name, :album, :artist, :length)
    end
end

final-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

final-rails/app/helpers/devise_helper.rb
# frozen_string_literal: true

# rubocop:disable Metrics/AbcSize, Metrics/MethodLength
# devise helper
module DeviseHelper
  def devise_error_messages!
    return if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:p, "- #{msg}.") }
                       .join
    sentence = I18n.t(
      "errors.messages.not_saved",
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase
    )

    html = <<-HTML
      <div class="bg-red-100 border-l-4 border-red-500 mb-4 p-4 text-red-700" role="alert">
          <p class="font-bold">Oops!</p>
          <p>#{sentence}</p>#{messages}
      </div>
    HTML

    html.html_safe
  end

  def devise_simple_error_messages!
    return if resource.errors.empty?

    sentence = "Ooops!"
    if resource.errors.count == 1
      message =  resource.errors.full_messages[0]
      html = <<-HTML
        <div class="bg-red-lightest border-l-4 border-red text-orange-dark p-4" role="alert">
          <p class="font-bold">#{sentence}</p>
          <p> #{message}.</p>
        </div>
      HTML
    else
      messages = resource.errors.full_messages.map { |msg| content_tag(:li, "#{msg}.") }
                         .join
      html = <<-HTML
        <div class="bg-red-100 border-l-4 border-red-500  mb-4 p-4 text-red-700" role="alert">
          <p class="font-bold">#{sentence}</p>
          <ul class="list-disc">
            #{messages}
          </ul>
        </div>
      HTML
    end

    html.html_safe
  end
end
# rubocop:enable Metrics/AbcSize, Metrics/MethodLength

final-rails/app/helpers/guest_helper.rb
module GuestHelper
end

final-rails/app/helpers/playlists_helper.rb
module PlaylistsHelper
end

final-rails/app/helpers/songs_helper.rb
module SongsHelper
end

final-rails/app/views/guest/index.html.erb
<div class="w-full text-center">
  <h1 class="font-bold text-4xl">Welcome!</h1>
  <p class="p-4 text-lg">To add a playlist, please <a href="/users/sign_in" class="underline text-blue-800">login</a> or <a href="/users/sign_up" class="underline text-blue-800">sign up.</a></p>

  <h2 class="font-bold text-3xl p-4">Here's Some Playlists Other Users Have Made!</h2>

  <div id="playlists" class="min-w-full">
    <% if !@playlists.empty? %>
    <div class="grid grid-cols-3 gap-4">
      
      <% @playlists.each do |playlist| %>
        <div class="shadow m-2 p-4 rounded">
          <%= render playlist %>
          <p class="p-2">
            <%= link_to "Login to View", playlist, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
          </p>
        </div>
      <% end %>
    <% else %>
      <p class="p-4 text-lg">There are no user added playlists yet... <a href="/users/sign_up" class="underline text-blue-800">Sign up</a> to add yours today!</p>
    <% end %>
    </div>
  </div>
</div>

final-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <nav class="bg-gray-800">
    <div class="mx-auto max-7xl px-2 sm:px-6 lg:px-8">
      <div class="relative flex items-center justify-between h-16">
        <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
          <div class="flex shrink-0 items-center">
            <a href="/">
              <img href="" class="h-8 w-auto invert" src="https://www.svgrepo.com/show/371935/home.svg" alt="Home">
            </a>
          </div>
          <div class="hidden sm:ml-6 sm:block">
            <div class="flex space-x-4">
              <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
              <a href="/playlists" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Playlists</a>
              <a href="/songs" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Songs</a>
              <!-- 
              <a href="#" class="rounded-md bg-gray-900 px-3 py-2 text-sm font-medium text-white" aria-current="page">Dashboard</a>
              <a href="#" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Team</a>
              <a href="#" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Projects</a>
              <a href="#" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Calendar</a>
              -->
            </div>
          </div>
        </div>
        <% if user_signed_in? %>
        <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
          <%= button_to "Sign out", destroy_user_session_path, class: "rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white", method: :delete %>
        </div>
      <% else %>
        <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
            <a href="users/sign_in" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Sign In</a>
        </div>
      <% end %>
      </div>
    </div>
  </nav>
  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

final-rails/app/views/playlists/_form.html.erb
<%= form_with(model: [@user, playlist], class: "contents") do |form| %>
  <% if playlist.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
        <% playlist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  
  <div class="my-5">
    <%= form.label :songs %>
    <table class="table-auto border-collapse block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full">
      <thead>
        <tr class="">
          <th></th>
          <th class="px-6 py-5">Song</th>
          <th class="px-6 py-5">Artist</th>
          <th class="px-6 py-5">Album</th>
        <tr>
      </thead>
      <tbody class="w-full">
        <% for song in Song.all %>
          <tr>
            <td class="px-6 py-5"><%= check_box_tag "playlist[song_ids][]", song.id, @playlist.songs.include?(song) %></td>
            <td class="px-6 py-5"><%= song.name %></td>
            <td class="px-6 py-5"><%= song.album %></td>
            <td class="px-6 py-5"><%= song.artist %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="my-5 hidden">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, value: current_user.id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full", :readonly => true %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

final-rails/app/views/playlists/_playlist.html.erb
<div id="<%= dom_id playlist %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= playlist.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= playlist.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= playlist.user_id %>
  </p>
  
  <div>
    <strong class="block font-medium mb-1">Songs:</strong>
    <table class="table-auto block rounded-md outline-none px-3 py-2 mt-2 w-full">
      <thead>
        <tr class="">
          <th class="px-6 py-5">Song</th>
          <th class="px-6 py-5">Artist</th>
          <th class="px-6 py-5">Album</th>
        <tr>
      </thead>
      <tbody class="w-full">
        <% for song in Song.all %>
          <% if playlist.songs.include?(song) %>
          <tr>
            <td class="px-3 py-2 text-md"><%= song.name %></td>
            <td class="px-3 py-2 text-md"><%= song.album %></td>
            <td class="px-3 py-2 text-md"><%= song.artist %></td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

final-rails/app/views/playlists/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing playlist</h1>

  <%= render "form", playlist: @playlist %>
  <%= link_to "Show this playlist", @playlist, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to playlists", playlists_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

  <div class="mx-auto py-5">
    <h1 class="text-3xl">Recommendations: </h1>
  </div>
  <table class="table-auto border-collapse block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full">
    <thead>
      <tr class="">
        <th></th>
        <th class="px-6 py-5">Song</th>
        <th class="px-6 py-5">Artist</th>
        <th class="px-6 py-5">Album</th>
      <tr>
    </thead>
    <tbody class="w-full">
      <% for song in Song.all %>
        <% if !@playlist.songs.include?(song) && !@playlist.songs.where(artist: song.artist).empty? %>
        <tr>
          <td class="px-6 py-5"><%= song.name %></td>
          <td class="px-6 py-5"><%= song.album %></td>
          <td class="px-6 py-5"><%= song.artist %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

</div>

final-rails/app/views/playlists/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Playlists" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Playlists</h1>
    <%= link_to "New playlist", new_playlist_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="playlists" class="min-w-full">
    <div class="grid grid-cols-3 gap-4 text-center">

      <% @playlists.each do |playlist| %>
        <div class="shadow m-2 p-4 rounded">
          <%= render playlist %>
          <p class="p-2">
            <%= link_to "Show This Playlist", playlist, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>

final-rails/app/views/playlists/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New playlist</h1>

  <%= render "form", playlist: @playlist %>

  <%= link_to "Back to playlists", playlists_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

final-rails/app/views/playlists/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @playlist %>

    <%= link_to "Edit this playlist", edit_playlist_path(@playlist), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to playlists", playlists_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this playlist", @playlist, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <div class="mx-auto py-5">
      <h1 class="text-3xl">Recommendations</h1>
    </div>
  </div>
</div>

final-rails/app/views/songs/_form.html.erb
<%= form_with(model: song, class: "contents") do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
        <% song.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  
  <div class="my-5">
    <%= form.label :artist %>
    <%= form.text_field :artist, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :album %>
    <%= form.text_field :album, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :length %>
    <%= form.number_field :length, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

final-rails/app/views/songs/_song.html.erb
<div id="<%= dom_id song %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= song.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Album:</strong>
    <%= song.album %>
  </p>
  
  <p class="my-5">
    <strong class="block font-medium mb-1">Artist:</strong>
    <%= song.artist %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Length:</strong>
    <%=song.length.to_s[0..-3]%>:<%=song.length.to_s.last(2)%>
  </p>

</div>

final-rails/app/views/songs/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing song</h1>

  <%= render "form", song: @song %>

  <%= link_to "Show this song", @song, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to songs", songs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

final-rails/app/views/songs/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Songs" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Songs</h1>
    <%= link_to "New song", new_song_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
  
  <div id="songs" class="min-w-full">
    <div class="grid grid-cols-3 gap-4 text-center">

      <% @songs.each do |song| %>
        <div class="shadow m-2 p-4 rounded">
          <%= render song %>
          <p class="p-2">
            <%= link_to "Show This Song", song, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>

final-rails/app/views/songs/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New song</h1>

  <%= render "form", song: @song %>

  <%= link_to "Back to songs", songs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

final-rails/app/views/songs/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @song %>

    <%= link_to "Edit this song", edit_song_path(@song), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to songs", songs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
        <% if user_signed_in? %>
        <%= button_to "Destroy this song", @song, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      <% else %>
        <!-- unauthorized users cannot delete a song -->
      <% end %>
    </div>
  </div>
</div>